// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvHvj2SvtsuPEcCftwQM0mIz-3vCQ9s10',
    appId: '1:597972730408:web:f588cecf1ce2b70ee0eb1d',
    messagingSenderId: '597972730408',
    projectId: 'businessplanning-development',
    authDomain: 'businessplanning-development.firebaseapp.com',
    storageBucket: 'businessplanning-development.firebasestorage.app',
    measurementId: 'G-KTWD43Y748',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb00xs_SPfgydXpDUbnoj5eBknhSOmExc',
    appId: '1:597972730408:android:7329357934690ad7e0eb1d',
    messagingSenderId: '597972730408',
    projectId: 'businessplanning-development',
    storageBucket: 'businessplanning-development.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAStHin_oh8Fm1gEIY9cZOinED9yKUFL7g',
    appId: '1:597972730408:ios:f003f9fe21dabc46e0eb1d',
    messagingSenderId: '597972730408',
    projectId: 'businessplanning-development',
    storageBucket: 'businessplanning-development.firebasestorage.app',
    iosBundleId: 'com.example.businessplanning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAStHin_oh8Fm1gEIY9cZOinED9yKUFL7g',
    appId: '1:597972730408:ios:f003f9fe21dabc46e0eb1d',
    messagingSenderId: '597972730408',
    projectId: 'businessplanning-development',
    storageBucket: 'businessplanning-development.firebasestorage.app',
    iosBundleId: 'com.example.businessplanning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvHvj2SvtsuPEcCftwQM0mIz-3vCQ9s10',
    appId: '1:597972730408:web:7a9f52fe19a23761e0eb1d',
    messagingSenderId: '597972730408',
    projectId: 'businessplanning-development',
    authDomain: 'businessplanning-development.firebaseapp.com',
    storageBucket: 'businessplanning-development.firebasestorage.app',
    measurementId: 'G-JG6FLTKXVT',
  );
}
